wherefunc: Notify if function was not found

diff --git a/bash/.config/bash/bash_functions b/bash/.config/bash/bash_functions
--- a/bash/.config/bash/bash_functions
+++ b/bash/.config/bash/bash_functions
@@ -20,7 +20,10 @@ __systemd_osc_context_escape() {
 wherefunc() (
 	local func_name="$1"
 	shopt -s extdebug
-	declare -F "$func_name"
+	declare -F "$func_name" || {
+		echo "${FUNCNAME[0]}: '$func_name' not found"
+		return 1
+	}
 )
 
 # Rename a function
