bash: output errors to stderr in shell functions

diff --git a/bash/.config/bash/functions b/bash/.config/bash/functions
--- a/bash/.config/bash/functions
+++ b/bash/.config/bash/functions
@@ -21,7 +21,7 @@ wherefunc() (
 	local func_name="$1"
 	shopt -s extdebug
 	declare -F "$func_name" || {
-		echo "${FUNCNAME[0]}: '$func_name' not found"
+		echo "${FUNCNAME[0]}: '$func_name' not found" >&2
 		return 1
 	}
 )
@@ -34,7 +34,7 @@ renamefunc() {
 	local new_name_sanitized="${new_name//[^[:alnum:]-_]/}"
 
 	if [[ "$new_name" != "$new_name_sanitized" ]]; then
-		echo "$0: '$new_name' is not a valid function name"
+		echo "$0: '$new_name' is not a valid function name" >&2
 		return 1
 	fi
 
